apiVersion: v1
appVersion: 2.17.0
description: CoreOS Dex
home: https://github.com/dexidp/dex/
icon: file://..icon.png
keywords:
- dex
- oidc
maintainers:
- email: Kevin.Fox@pnnl.gov
  name: kfox1111
- email: shane.starcher@gmail.com
  name: sstarcher
- email: pete.brown@powerhrg.com
  name: rendhalver
name: dex
version: 1.5.1
