description: An nginx Ingress controller that uses ConfigMap to store the nginx configuration.
engine: gotpl
icon: file://..icon.png
keywords:
- ingress
- nginx
maintainers:
- email: jack.zampolin@gmail.com
  name: Jack Zampolin
- email: mgoodness@gmail.com
  name: Michael Goodness
- email: chance.zibolski@coreos.com
  name: Chance Zibolski
name: nginx-ingress
sources:
- https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx
version: 0.3.1
