appVersion: 0.9.0-beta.7
description: An nginx Ingress controller that uses ConfigMap to store the nginx configuration.
engine: gotpl
icon: file://../icon.png
keywords:
- ingress
- nginx
maintainers:
- email: jack.zampolin@gmail.com
  name: jackzampolin
- email: mgoodness@gmail.com
  name: mgoodness
- email: chance.zibolski@coreos.com
  name: chancez
name: nginx-ingress
sources:
- https://github.com/kubernetes/contrib/tree/master/ingress/controllers/nginx
version: 0.7.1
