apiVersion: v1
appVersion: 0.5.0
description: G2 by AppsCode - Gearman in Golang
home: https://github.com/appscode/g2
icon: file://../icon.png
maintainers:
- email: support@appscode.com
  name: appscode
name: g2
sources:
- https://github.com/appscode/g2
version: 0.3.2
