description: GitLab Enterprise Edition
home: https://about.gitlab.com
icon: file://../icon.png
keywords:
- git
- ci
- deploy
- issue tracker
- code review
- wiki
maintainers:
- email: contact@quent.in
  name: Quentin Rousseau
name: gitlab-ee
sources:
- https://hub.docker.com/r/gitlab/gitlab-ee/
- https://docs.gitlab.com/omnibus/
version: 0.1.6
