appVersion: 15.0.2
description: A file sharing server that puts the control and security of your own
  data back into your hands.
home: https://nextcloud.com/
icon: file://../icon.svg
keywords:
- nextcloud
- storage
- http
- web
- php
maintainers:
- email: christian.ingenhaag@googlemail.com
  name: chrisingenhaag
name: nextcloud
sources:
- https://github.com/nextcloud/docker
version: 1.0.2
