description: Distributed computation in Python
home: https://github.com/dask/distributed
icon: file://../icon.png
maintainers:
- email: df.rodriguez143@gmail.com
  name: danielfrg
name: dask-distributed
sources:
- https://github.com/dask/distributed
version: 1.16.4
