apiVersion: v1
appVersion: 0.13.0
description: Chaoskube periodically kills random pods in your Kubernetes cluster.
engine: gotpl
home: https://github.com/linki/chaoskube
icon: file://..icon.png
keywords:
- chaos-monkey
- chaos-engineering
maintainers:
- email: linki+kubernetes.io@posteo.de
  name: linki
name: chaoskube
sources:
- https://github.com/linki/chaoskube
version: 3.0.0
