description: Prometheus is a monitoring system and time series database.
engine: gotpl
home: https://prometheus.io/
icon: file://../icon.png
maintainers:
- email: mgoodness@gmail.com
  name: Michael Goodness
name: prometheus
sources:
- https://github.com/prometheus/alertmanager
- https://github.com/prometheus/prometheus
- https://github.com/prometheus/pushgateway
- https://github.com/kubernetes/kube-state-metrics
version: 4.5.0
