appVersion: 0.18.1
description: Distributed computation in Python with task scheduling
home: https://dask.pydata.org
icon: file://../icon.png
maintainers:
- email: df.rodriguez143@gmail.com
  name: danielfrg
- email: mrocklin@gmail.com
  name: mrocklin
name: dask
sources:
- https://github.com/dask/dask
version: 1.1.0
