apiVersion: v1
appVersion: 3.7.12
description: Highly available RabbitMQ cluster, the open source message broker software
  that implements the Advanced Message Queuing Protocol (AMQP).
home: https://www.rabbitmq.com
icon: file://../icon.png
keywords:
- rabbitmq
- message queue
- AMQP
- AMQPS
- MQTT
- STOMP
maintainers:
- email: ssheehy@firescope.com
  name: steven-sheehy
name: rabbitmq-ha
sources:
- https://github.com/rabbitmq/rabbitmq
- https://github.com/docker-library/rabbitmq
version: 1.25.0
