apiVersion: v1
appVersion: 2.0.2
description: Centrifugo is a real-time messaging server.
home: https://github.com/centrifugal/centrifugo
icon: file://..icon.png
keywords:
- centrifugo
- websocket
- golang
maintainers:
- email: ozimok.oleg@gmail.com
  name: oleh-ozimok
name: centrifugo
version: 3.0.0
