description: Concourse is a simple and scalable CI system.
engine: gotpl
home: https://concourse.ci/
icon: file://../icon.png
keywords:
- ci
- concourse
- concourse.ci
maintainers:
- email: frodenas@gmail.com
  name: Ferran Rodenas
name: concourse
sources:
- https://github.com/concourse/bin
- https://github.com/kubernetes/charts
version: 0.2.0
