appVersion: 4.1.2
description: OrangeHRM is a free HR management system that offers a wealth of modules
  to suit the needs of your business.
engine: gotpl
home: https://www.orangehrm.com
icon: file://../icon.png
keywords:
- orangehrm
- http
- https
- web
- application
- php
- human resources
maintainers:
- email: containers@bitnami.com
  name: bitnami-bot
name: orangehrm
sources:
- https://github.com/bitnami/bitnami-docker-orangehrm
version: 3.0.1
