appVersion: 1.0.4
description: Fast and Lightweight Log/Data Forwarder for Linux, BSD and OSX
home: http://fluentbit.io
icon: file://../icon.png
keywords:
- logging
- monitoring
- fluent
- fluentd
maintainers:
- email: Kevin.Fox@pnnl.gov
  name: kfox1111
- email: eduardo@treasure-data.com
  name: edsiper
name: fluent-bit
sources:
- http://fluentbit.io
version: 1.8.0
