apiVersion: v1
appVersion: 6.5.1
description: A Helm chart to collect Kubernetes logs with metricbeat
home: https://www.elastic.co/products/beats/metricbeat
icon: file://..icon.svg
maintainers:
- email: atushi.k@gmail.com
  name: at-k
- email: ykuoka@gmail.com
  name: mumoshu
name: metricbeat
sources:
- https://www.elastic.co/guide/en/beats/metricbeat/current/index.html
version: 0.4.0
