apiVersion: v1
description: Scales worker nodes within agent pools
icon: file://../icon.png
maintainers:
- email: ritazh@microsoft.com
  name: Rita Zhang
name: acs-engine-autoscaler
sources:
- https://github.com/wbuchwalter/Kubernetes-acs-engine-autoscaler
version: 0.1.0
