apiVersion: v1
appVersion: '3'
description: Agent for Buildkite
home: https://buildkite.com
icon: file://../icon.png
keywords:
- kubernetes deployment
- helm release
- continuous deployment
- continuous integration
maintainers:
- email: rmocius@gmail.com
  name: rimusz
name: buildkite
sources:
- https://github.com/buildkite/agent
version: 0.1.0
