appVersion: 4.8.3
description: phpMyAdmin is an mysql administration frontend
engine: gotpl
home: https://www.phpmyadmin.net/
icon: file://../icon.png
keywords:
- mariadb
- mysql
- phpmyadmin
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: phpmyadmin
sources:
- https://github.com/bitnami/bitnami-docker-phpmyadmin
version: 1.2.2
