apiVersion: v1
appVersion: 2.6.2
description: A Helm chart for Docker Registry
home: https://hub.docker.com/_/registry/
icon: file://..icon.png
maintainers:
- email: jpds@protonmail.com
  name: jpds
name: docker-registry
sources:
- https://github.com/docker/distribution-library-image
version: 1.0.5
