apiVersion: v1
appVersion: 0.4.0
description: Kubed by AppsCode - Kubernetes daemon
home: https://github.com/appscode/kubed
icon: file://..icon.png
maintainers:
- email: support@appscode.com
  name: appscode
name: kubed
sources:
- https://github.com/appscode/kubed
version: 0.2.0
