description: Chart for Telegraf Kubernetes deployments
engine: gotpl
home: https://www.influxdata.com/time-series-platform/telegraf/
icon: file://../icon.png
keywords:
- telegraf
- collector
- timeseries
- influxdata
maintainers:
- email: jack@influxdb.com
  name: Jack Zampolin
name: telegraf
version: 0.1.0
