apiVersion: v1
appVersion: 0.5.14
description: 'Configure external DNS servers (AWS Route53, Google CloudDNS and others)

  for Kubernetes Ingresses and Services

  '
engine: gotpl
home: https://github.com/kubernetes-incubator/external-dns
icon: file://../icon.png
maintainers:
- email: rabadin@cisco.com
  name: rabadin
name: external-dns
sources:
- https://github.com/kubernetes-incubator/external-dns
version: 1.7.10
