appVersion: 2.10.0
description: CoreOS Dex
home: https://github.com/coreos/dex/
icon: file://../icon.png
keywords:
- dex
- oidc
maintainers:
- email: Kevin.Fox@pnnl.gov
  name: kfox1111
- email: shane.starcher@gmail.com
  name: sstarcher
name: dex
version: 0.3.1
