appVersion: 0.14.0
description: An nginx Ingress controller that uses ConfigMap to store the nginx configuration.
engine: gotpl
home: https://github.com/kubernetes/ingress-nginx
icon: file://..icon.png
keywords:
- ingress
- nginx
maintainers:
- email: jack.zampolin@gmail.com
  name: jackzampolin
- email: mgoodness@gmail.com
  name: mgoodness
- email: chance.zibolski@coreos.com
  name: chancez
name: nginx-ingress
sources:
- https://github.com/kubernetes/ingress-nginx
version: 0.19.1
