appVersion: '3.4'
description: NoSQL document-oriented database that stores JSON-like documents with
  dynamic schemas, simplifying the integration of data in content-driven applications.
home: https://github.com/mongodb/mongo
icon: file://../icon.jpg
maintainers:
- email: ramanathana@google.com
  name: foxish
- email: unguiculus@gmail.com
  name: unguiculus
name: mongodb-replicaset
sources:
- https://github.com/mongodb/mongo
version: 2.2.1
