apiVersion: v1
appVersion: '8.17'
description: Sentry is a cross-platform crash reporting and aggregation platform.
home: https://sentry.io/
icon: file://..icon.png
keywords:
- debugging
- logging
maintainers:
- email: justin@linux.com
  name: rothgar
name: sentry
sources:
- https://github.com/getsentry/sentry
version: 0.1.8
