apiVersion: v1
appVersion: 11.0.20190215
description: A suite of web based open source business apps.
engine: gotpl
home: https://www.odoo.com/
icon: file://../icon.png
keywords:
- odoo
- crm
- www
- http
- web
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: odoo
sources:
- https://github.com/bitnami/bitnami-docker-odoo
version: 6.0.1
